test:
    config: My config value prod profile
  
spring:
    datasource:
        url: jdbc:postgresql://hr-worker-pg12:5432/db_hr_worker
        username: postgres
        password: 1234567
    jpa:
        hibernate:
            ddl-auto: update
